---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: golang-hello-world-web-pdb
spec:
  maxUnavailable: 1 # stresses availability - only 1 unavailable at a time
  selector:
    matchLabels:
      app: golang-hello-world-web
